### ISSUE TITLE
Series's Avg Value Unexpected as Infinity

### ISSUE THREAD

**Issue by abramjstamper** [esnet/pond#123]
I have a strange issue that just started appearing when I moved the pondjs time series processing from the React client to the server side. While this might be totally unrelated, I wasn't seeing this issue until I made the switch. I am rendering a channels chart with 6 channels each within the same range. I wanted to help reduce render times on the client and shove it off on the server. However, I still generate avg, min, stdev, max on the client. Instead of creating the time series on the client, I send a string representation to the client and put it in the argument to a `new TimeSeries()` object. Whenever I call `avg` on 2 of my 6 series, I get Infinity as a result. Both the `min` and `max` functions work though.

Here's a snippet of the client code I currently have in my `componentDidMount()`. The data is the time series data in an object with the key being the channel name, and the value being the time series.
```
import { TimeSeries, filter } from 'pondjs';

  componentDidMount() {
    const { data, range } = this.props.chartData;
    Object.keys(data).forEach(channel => {
      const state = {...this.state};
      state.channels.push(channel);
      state.chartData[channel] = {};
      const series = new TimeSeries(data[channel]);
      state.chartData[channel].series = series;
      state.chartData[channel].avg = series.avg(channel, filter.ignoreMissing);
      state.chartData[channel].min = series.min(channel);
      state.chartData[channel].max = series.max(channel);
      this.setState(state);
    });

    console.log(this.state);
  }
```

Server code. I'm not sure if I'm doing the `fieldSpec` incorrectly, where it would create this issue.
```
 response = new TimeSeries({ name: 'counts', columns: ['time', 'counts'], points: temp.counts }).fill({ fieldSpec: 'counts' });
```

I checked around and saw someone else having an issue (#69) but it was quite some time ago. However, the suggestion of adding in a filter was something that I attempted to see if it would resolve the issue and it did not make a difference. You'll see in my snippet above that I have `filter.ignoreMissing`.

[Here's a pastebin of the data that is causing the issue - provided by JSON.stringify](https://paste.ee/p/c36OB)

Any assistance is appreciated. I'm not sure if this is a feature or a bug.

**Comment by abramjstamper** [comment]
UPDATE:

When I moved the `avg` to the server trying to `console.log` it, I got this error message. I have listed it below.

This server side code generated that error:
```
console.log(data.counts.avg(counts));
```
I also tried it with a filter. I got the same error. This is the code I used to add the filter.
```
console.log(data.counts.avg(counts, filter.ignoreMissing));
```

```
TypeError: fieldPath.split is not a function
    at Collection.aggregate (/home/abramjstamper/Documents/azure-processing/azure-rest-api/node_modules/pondjs/lib/lib/collection.js:1002:35)
    at Collection.avg (/home/abramjstamper/Documents/azure-processing/azure-rest-api/node_modules/pondjs/lib/lib/collection.js:852:25)
    at TimeSeries.avg (/home/abramjstamper/Documents/azure-processing/azure-rest-api/node_modules/pondjs/lib/lib/timeseries.js:948:37)
    at handler (/home/abramjstamper/Documents/azure-processing/azure-rest-api/src/plugins/diagnostics/charts.js:81:45)
```
